dorny/test-reporter

src/utils/markdown-utils.ts
- Use the ✅ for passed tests
- Use the ⚪ for skipped tests
=> Fix #199: Use ✅ instead of ✔️ for better cross platform look

README.md
Add a note to signify that a workflow-triggered run (needed for public forkable repos) won't execute in a PR and must be merged into `main` first.
I stumbled upon this while following the instructions here in the `readme.md` and I couldn't get the PR to show the report. The cause of that is described here: https://github.com/orgs/community/discussions/25288.
Basically: create the workflow file, merge to `main` and only then a new PR (forked or otherwise) will pick up on the added workflow.
Found while working on https://github.com/fsprojects/FSharp.Control.TaskSeq/pull/101, and that PR didn't show the changes. After merge, it did show up in https://github.com/fsprojects/FSharp.Control.TaskSeq/pull/103.
=> Improve clarity on configuring for forkable repos

README.md, action.yml
"Coma separated" -> "Comma-separated"
=> Correct typo in docs

README.md, action.yml, dist/index.js, src/main.ts
There are use-cases where you wouldn't necessarily want the action to fail if no test results were found (it could just mean that no test results were run). This PR supports not failing the job if no results are found.
=> add feature fail-on-empty

README.md, dist/index.js, src/main.ts
* Add new outputs (url, url_html)
* Update readme
=> Add new output for url url html

README.md
I had issues with setting --reporters=jest-Junit". I found I needed to use --reporters=jest-junit" instead.
=> Update jest-Junit part of Readme

action.yml
Hello
Thank you for sharing this cool action.
A couple of the action fields that uses default values are also marked as required,
I keep seeing errors in my _vscode_ so I pushed this small fix.
Thanks!
:-)
=> fix: default-valued fields are not mandatory

action.yml
It seems the outputs `url` and `url_html` had not been declared in 2868c9aa28a8542fae47110cb1354b76612dd485 as action outputs.
In my runs, both outputs are not available.
=> declare 'url' and 'url_html' as action outputs

dist/index.js, src/utils/parse-utils.ts
Some reports don't include a stack trace or details on the failure.
This can happen, for example, for junit reports that are used with non Java tests or when subtests are used. See https://github.com/dorny/test-reporter/issues/256 https://github.com/dorny/test-reporter/issues/241 or https://github.com/dorny/test-reporter/issues/239 (there may be others)
Just ignore the stacktrace if it is not defined.
=> Avoid split on undefined

README.md, __tests__/__outputs__/swift-xunit.md, __tests__/__snapshots__/swift-xunit.test.ts.snap, __tests__/fixtures/swift-xunit.xml, __tests__/swift-xunit.test.ts, action.yml, src/main.ts, src/parsers/swift-xunit/swift-xunit-parser.ts
The Swift tests results file is in xUnit format which is compatible with the `JavaJunitParser`.
=> Add `SwiftXunitParser` class based on `JavaJunitParser` for `swift-xunit` reporter

__tests__/__outputs__/jest-react-component-test-results.md, __tests__/__snapshots__/jest-junit.test.ts.snap, __tests__/fixtures/external/jest/jest-react-component-test-results.xml, __tests__/jest-junit.test.ts, dist/index.js, src/parsers/jest-junit/jest-junit-parser.ts
=> Escape <> characters in suite name

package-lock.json, package.json
Merging the code from [release v1.7.0](https://github.com/dorny/test-reporter/tree/v1.7.0) to `main` to keep the commits in order.
=> Merge v1.7.0 release to main

README.md, __tests__/__outputs__/rspec-json.md, __tests__/__snapshots__/rspec-json.test.ts.snap, __tests__/fixtures/empty/rspec-json.json, __tests__/fixtures/rspec-json.json, __tests__/rspec-json.test.ts, action.yml, dist/index.js, src/main.ts, src/parsers/rspec-json/rspec-json-parser.ts, src/parsers/rspec-json/rspec-json-types.ts
Added support for the Rspec test suite (Ruby).
The result JSON is very similar to the one generated by the mocha Test framework, so the new parser has almost the same behavior.
=> Add support for Rspec (Ruby)

__tests__/fixtures/empty/dart-json.json, dist/index.js, reports/dart/pubspec.lock, reports/dart/pubspec.yaml, src/parsers/dart-json/dart-json-parser.ts
Fixes #319 
According to the documentation of the [TestDoneEvent](https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md#testdoneevent), the hidden "tests" should be ignored:
> The `hidden` attribute indicates that the test's result should be hidden and not
counted towards the total number of tests run for the suite. This is true for
virtual tests created for loading test suites, `setUpAll()`, and
`tearDownAll()`. Only successful tests will be hidden.
- updated \_\_tests\_\_ to fail if hidden tests are counted toward total number of tests
- filter out any "tests" if their TestDoneEvent has `hidden` flag set to `true`
- cross-checked on a repo with ~2,500 tests
=> fix: reporting wrong number of tests in Dart

dist/index.js, src/utils/github-utils.ts
Here is an alternative solution to #436. It delegates the redirect-handling to the `got` library, instead of fixing the manual handling. This should fix #343 and fix #363, just as the original solution.
=> Fix problematic retransmission of authentication token (alternative solution)

README.md, __tests__/__outputs__/dotnet-nunit.md, __tests__/__snapshots__/dotnet-nunit.test.ts.snap, __tests__/dotnet-nunit.test.ts, __tests__/fixtures/dotnet-nunit.xml, __tests__/fixtures/external/nunit-sample.xml, action.yml, dist/index.js, package.json, reports/dotnet/DotnetTests.NUnitV3Tests/CalculatorTests.cs, reports/dotnet/DotnetTests.NUnitV3Tests/DotnetTests.NUnitV3Tests.csproj, reports/dotnet/DotnetTests.sln, src/main.ts, src/parsers/dotnet-nunit/dotnet-nunit-parser.ts, src/parsers/dotnet-nunit/dotnet-nunit-types.ts, src/parsers/rspec-json/rspec-json-parser.ts, src/parsers/rspec-json/rspec-json-types.ts
This is important for displaying the results generated by the Unity Test Framework, among probably other uses. It builds on the work started in the https://github.com/dorny/test-reporter/tree/dotnet-nunit branch.
I struggled a little bit with how to translate the format's arbitrarily-nested suites to the test-reporter's suite, group, test structure. In the end I made the last suite before the test case the "group", and flattened any suites above that into a single suite. Except that it ignores suites of type "Theory". So basically test fixtures (classes) will be groups, and assemblies/projects will be suites. Other things are definitely possible.
Fixes #98
=> Add support for NUnit v3 XML results files

__tests__/__outputs__/swift-xunit.md, __tests__/__snapshots__/java-junit.test.ts.snap, __tests__/__snapshots__/swift-xunit.test.ts.snap, dist/index.js, src/parsers/java-junit/java-junit-parser.ts, src/parsers/java-junit/java-junit-types.ts
FYI in the tests it looked like the `message` attribute was working because the first line of the node's `text` happened to match the message attribute.
=> Fix JUnit message / type fields.

README.md
With mocha#4607 fixed and published in [v9.1.0](https://github.com/mochajs/mocha/releases/tag/v9.1.0), users can output valid json using mocha's JSON reporter and the `--reporter-option output={filename}` option, provided version 9.1.0 or above is used.
This PR updates the readme to reflect this.
=> Update mocha-json usage instructions

__tests__/__outputs__/jest-junit-eslint.md, __tests__/__snapshots__/jest-junit.test.ts.snap, __tests__/fixtures/jest-junit-eslint.xml, __tests__/jest-junit.test.ts, dist/index.js, src/parsers/jest-junit/jest-junit-parser.ts
The [ESLint junit formatter](https://www.npmjs.com/package/eslint-junit) does not include a total time attribute for the root `<testsuites>` element.
This PR makes the parser a little bit more lenient to accept `testsuites` elements without any attributes at all.
=> Fix parsing of ESLint reports in jest-junit format

__tests__/__outputs__/dart-json.md, __tests__/__outputs__/dotnet-nunit.md, __tests__/__outputs__/dotnet-trx.md, __tests__/__outputs__/fluent-validation-test-results.md, __tests__/__outputs__/jest-junit-eslint.md, __tests__/__outputs__/jest-junit.md, __tests__/__outputs__/jest-react-component-test-results.md, __tests__/__outputs__/jest-test-results.md, __tests__/__outputs__/junit-with-message.md, __tests__/__outputs__/mocha-json.md, __tests__/__outputs__/mocha-test-results.md, __tests__/__outputs__/provider-test-results.md, __tests__/__outputs__/pulsar-test-results-no-merge.md, __tests__/__outputs__/pulsar-test-results.md, __tests__/__outputs__/rspec-json.md, __tests__/__outputs__/silent-notes-test-results.md, __tests__/__outputs__/swift-xunit.md, dist/index.js, src/report/get-report.ts, src/utils/slugger.ts
Ensure that links include the `user-content-` prefix when displaying in Actions Summary.
Resolves #566
=> Fix broken links in report summary

dist/index.js, src/report/get-report.ts
This PR aligns the limit of the allowed 'step-summary' report size for the action with the GitHub limit for the GITHUB_STEP_SUMMARY (https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#step-isolation-and-limits)
Test run: https://github.com/OlesGalatsan/test-trx/actions/runs/15045312655#summary-42286264533
=> Increase step summary limit to 1MiB

__tests__/dotnet-trx.test.ts, __tests__/fixtures/empty/dotnet-trx-empty-test-definitions.trx, dist/index.js, src/parsers/dotnet-trx/dotnet-trx-parser.ts
This PR is a fix for https://github.com/phoenix-actions/test-reporting/issues/64 that is also relevant for this action.
Currently, this action only checks if TestDefinitions are not defined, but it is possible that it will just be empty:
```
<?xml version="1.0" encoding="utf-8"?>
<TestRun id="f4386078-5371-420d-b9c6-122f1e77f109" name="test" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
<Times creation="2025-05-13T12:53:18.295323Z" queuing="2025-05-13T12:53:18.295323Z" start="2025-05-13T12:53:18.295323Z" finish="2025-05-13T12:53:18.4362393Z" />
<TestSettings name="default" id="f25a2621-1af4-4d50-a859-619a3039691e">
<Deployment runDeploymentRoot="test" />
</TestSettings>
<Results />
<TestDefinitions />
<TestEntries />
<TestLists>
<TestList name="Results Not in a List" …
```
=> Fix for empty TRX TestDefinitions

dist/index.js, src/main.ts
When using 'checks' the short summary is used for a better visualization of test results:
This PR adds the same short summary when using 'actions-summary'.
Test runs: https://github.com/OlesGalatsan/MstTrx/actions/runs/15133915790
=> Add step summary short summary

__tests__/__outputs__/dart-json.md, __tests__/__outputs__/dotnet-nunit.md, __tests__/__outputs__/dotnet-trx.md, __tests__/__outputs__/fluent-validation-test-results.md, __tests__/__outputs__/golang-json.md, __tests__/__outputs__/jest-junit-eslint.md, __tests__/__outputs__/jest-junit.md, __tests__/__outputs__/jest-react-component-test-results.md, __tests__/__outputs__/jest-test-results.md, __tests__/__outputs__/junit-with-message.md, __tests__/__outputs__/mocha-json.md, __tests__/__outputs__/mocha-test-results.md, __tests__/__outputs__/provider-test-results.md, __tests__/__outputs__/pulsar-test-results-no-merge.md, __tests__/__outputs__/pulsar-test-results.md, __tests__/__outputs__/rspec-json.md, __tests__/__outputs__/silent-notes-test-results.md, __tests__/__outputs__/swift-xunit.md, dist/index.js, src/report/get-report.ts
In this PR https://github.com/dorny/test-reporter/pull/463 (https://github.com/dorny/test-reporter/pull/463/files#diff-22731215fc33a13afdd1303998ef7ad6d3fbc438e9dd79bfe13be7348890ca0fR161), for some reason anchor links were removed from the summary table. This makes harder to navigate the report when there is a lot of tests in different suites. 
This PR reverts that change and ensures the correct anchor links are used when there are some empty tests that are not visualized in the summary table.
=> Return links to summary report

__tests__/__outputs__/dotnet-trx-only-failed.md, __tests__/__outputs__/dotnet-trx.md, __tests__/__snapshots__/dotnet-trx.test.ts.snap, dist/index.js, src/parsers/dotnet-trx/dotnet-trx-parser.ts
This update allows displaying a stack trace for failed tests in trx file directly in GitHub summary as it's already available for some other report types.
=> Add stack trace from trx to summary

action.yml
Fixes missing attribute from PR #568
Implement the simpler part of the #610:
> The first issue was that the new report-title option is missing from the GitHub Action's input. The mentioned PR added the back end logic, tests and even updated the documentation, but missed adding it to the action.
=> Define the `report-title` attribute in action definition

dist/index.js, src/parsers/dotnet-nunit/dotnet-nunit-parser.ts
Fixes error `no-shadow`: Disallow variable declarations from shadowing variables declared in the outer scope.
=> Fix `no-shadow`: Disallow variable declarations from shadowing variables declared in the outer scope
